# Generated by Django 4.0.6 on 2024-05-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0004_pais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pais',
            new_name='Paises',
        ),
    ]
