# Generated by Django 4.0.6 on 2024-05-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0005_rename_pais_paises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paises',
            new_name='Pais',
        ),
    ]
