databases:
  - name: servidorVictor
    plan: free
    databaseName: dbcine
    user: victor

services:
  - type: web
    plan: free
    name: cineUtc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUtc.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorVictor
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutcdeployment.onrender.com


# set DATABASE_URL=postgresql://dbcine_juv2_user:7kwGiVmgoLZXypNWPRjeklULtMV9eac6@dpg-cqlpk9t6l47c73fj7b2g-a.oregon-postgres.render.com/dbcine_juv2